version: '3'
#Mock Docker Compose
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATA_URL=postgres://postgres
    depends_on:
      - db

  db:
    image: postgres/postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
